### ISSUE TITLE
Postal codes with leading 0s render to different values

### ISSUE THREAD

**Issue by mikemahoney218** [quarto-journals/elsevier#12]
Given the input file:
````
---
title: "Example reprex"
format:
  elsevier-pdf: default
author:
  - name: Author One
    affiliations:
      - ref: InstOne
  - name: Author Two
    affiliations:
      - ref: InstTwo
affiliations:
  - id: InstOne
    name: Some Place
    department: Some Address
    city: Syracuse, NY
    country: USA
    postal-code: 13210
  - id: InstTwo
    name: Some Place
    address: Some Address
    city: Boston, MA
    country: USA
    postal-code: 02210
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

````

InstTwo will render as "Some Place, Some Address, Boston, MA, USA, 1160". The problem is that the postal code 02210 appears to be transformed into 1160. This does not happen if the postal code is quoted or does not begin with a 0.
