### ISSUE TITLE
Put the title and abstract on their own page: does this actually work?

### ISSUE THREAD

**Issue by presnell** [quarto-journals/elsevier#14]
I have tried to follow the instructions to put the title and abstract on their own page using
```
format:
  elsevier-pdf:
    journal:
      cite-style: number
    include-in-header: 
      text: |
        \newpageafter{author}
```
and as far as I can tell it has no effect at all.  Assuming that I'm missing something, could a working template that uses this option be provided?
