### ISSUE TITLE
cross referencing latex tables in elseveier quarto template

### ISSUE THREAD

**Issue by jpatteet** [quarto-journals/elsevier#17]
I would like to cros reference a latex table in my text.
Originally I was not using the elsevier template and the solution I used was adding the following packages.

```
---
format: pdf
header-includes:
  - \usepackage{hyperref}
  - \usepackage[capitalise,noabbrev]{cleveref}
---
```
I can then cross ref a latex table using `\cref{Variabilities}`

(because I have `\label{Variabilities}` in my table)

I tried using the same idea in the elsevier template 

```
---
format:
  elsevier-pdf:
    keep-tex: true
    include-in-header: |
      \usepackage{multirow}
      \usepackage{hyperref}
      \usepackage[capitalise,noabbrev]{cleveref}
    journal:
      name: Forensic Science International
      formatting: preprint
      model: 3p
      cite-style: authoryear
---
```

But I always get the same error:

```
updating tlmgr
updating existing packages
compilation failed- error
Undefined control sequence.
l.887 information (W or B as explained in \cref{Variabilities})
```

Any idea how I could work around this issue ?

**Comment by dragonstyle** [comment]
I'm not seeing an error with PDF rendering when I do use the following:


```yaml
format:
  elsevier-pdf:
    keep-tex: true
    include-in-header:
      text: |
        \usepackage{multirow}
        \usepackage{hyperref}
        \usepackage[capitalise,noabbrev]{cleveref}
    journal:
      name: Forensic Science International
      formatting: preprint
      model: 3p
      cite-style: authoryear
```

When I use you example which includes `include-in-header`, I do see an error in Quarto output (though rendering appears to continue, which seems bad). `include-in-header` when used directly is expecting a file path whose contents will be placed verbatim in the header. The `text` subkey lets Quarto know that this is text (not a file)...

Does that fix it for you as well?
