### ISSUE TITLE
Issues with yml example in Readme

### ISSUE THREAD

**Issue by eeholmes** [quarto-journals/elsevier#2]
This is in the Readme:
```
  elsevier-pdf:
    journal:
      formatting: preprint
      model: 3p
      layout: twocolumn
      cite-style: numbered
      graphical-abstract: "![](abstract.png)"
      highlights:
        - Highlight 1
        - Highlight 2 
        - Highlight 3
```

Issues:

* `cite-style: numbered` needs to be `cite-style: number` (as suggested by error msg) 
* graphical abstract doesn't really work with `layout: twocolum`. Way too much spacing. Works normally with onecolumn layout. This is a cls issue, but maybe not best example yaml since it looks awful.
* Same with highlights. Looks very bad w twocolumn layout.

Suggestion, these examples yamls?

Two column format
```
  elsevier-pdf:
    journal:
      formatting: preprint
      model: 3p
      layout: twocolumn
      cite-style: number
```

Include a graphical abstract and highlights.
```
  elsevier-pdf:
    journal:
      cite-style: authoryear
      graphical-abstract: "![](abstract.png)"
      highlights:
        - Highlight 1
        - Highlight 2 
        - Highlight 3
```

Include a graphical abstract and highlights.
```
  elsevier-pdf:
    journal:
      cite-style: authoryear
      graphical-abstract: "![](abstract.png)"
      highlights:
        - Highlight 1
        - Highlight 2 
        - Highlight 3
```

Put the title and abstract on their own page.
```
  elsevier-pdf:
    journal:
      cite-style: number
    include-in-header: 
      text: |
        \newpageafter{author}
```

Pass in class options to the elsevier cls. See  [elsdoc.pdf](https://github.com/quarto-journals/elsevier/blob/main/style-guide/elsdoc.pdf) for available options. **Note this doesn't actually work for all the options. Seems like there is overriding happening since options like `review` and `endfloat` did nothing. but `lefttitle` works.**
```
  elsevier-pdf:
    journal:
      cite-style: number
    include-in-header: 
      text: |
        \newpageafter{author}
    classoption: [lefttitle]
```
