### ISSUE TITLE
Equal-contributors option

### ISSUE THREAD

**Issue by jgilis** [quarto-journals/elsevier#20]
Hi,

I would like to toggle on the equal-contributors attribute in the Elsevier template. I'm trying to achieve this with:

```
  - name: Name1 LastName1 
    attributes:
      corresponding: TRUE
      equal-contributor: TRUE
  - name: Name2 LastName2 
    url: 0009-0000-0345-1227
    attributes:
      equal-contributor: TRUE
  - name: Name3 LastName3
```

in my `.qmd` header, but without success. Note that the `corresponding` attribute is working correctly. Is the `equal-contributor` available form the elsevier template?

Kind regards,

Jeroen

**Comment by dragonstyle** [comment]
In looking at the title block that we are currently generating for Elsevier, it doesn't currently support equal-contributor as an option. Is there a specific treatment that Elsevier provides for equal contributors? I can try to improve if you can point me at something to shoot for...

**Comment by hughgifford** [comment]
I would also love to have this feature. Thank you

**Comment by jgilis** [comment]
I am unsure if this applies to all elsevier journals, but `molecular cell`, for instance, says the following: " In addition to noting corresponding authors with an asterisk, you may use numbered footnotes to designate senior authors and otherwise equally contributing authors. The following footnote should be used for authors who have made equal contributions: “6These authors contributed equally”." (link: https://www.cell.com/molecular-cell/authors#:~:text=The%20following%20footnote%20should%20be,describe%20each%20author's%20specific%20contributions).

So essentially, they are treated pretty similarly to affiliations (an extra number), only they should ideally appear in the footnotes. As a temporary hack, I simply added it to affiliations like this:

```
author: 
  - name: Author 1
    corresponding: TRUE
    affiliations:
      - name: These authors contributed equally
      - name: Ghent University
        city: Ghent
  - name: Author 2
    affiliations:
      - name: These authors contributed equally
      - name: Padova University
        city: Padova
```

 To be fair, this could be sufficient for me, and I don't think I will necessarily follow up this "issue". But to really adhere to `molecular cell`, and to allow for full flexibility, the `equal-contributors` argument should be used like it is implemented for other templates.
