### ISSUE TITLE
Remove trailing comma in affiliations

### ISSUE THREAD

**Issue by jgilis** [quarto-journals/elsevier#23]
Hi,

I just noticed that with multiple affiliations, a trailing comma appears.

For instance, if I do:

```
author: 
  - name: Author1
    affiliations:
      - name: Ghent University
        city: Ghent
  - name: Author2
    affiliations:
      - name: Padova University
        city: Padova
```

I get the following:

<img width="510" alt="Screen Shot 2023-11-22 at 12 59 47" src="https://github.com/quarto-journals/elsevier/assets/32977858/7dddc5dd-115b-4c06-8b01-d3da9eb25a36">

If possible, could the trailing comma on the last line be removed?

Jeroen
